/**
 * Phase B codegen: read catalog.authoritative.json and emit src/generated/api.ts
 * — one typed class per service, one method per catalog RPC method, with args
 * built automatically from each param's `kind`. Run:
 *   npx ts-node tools/gen_client.ts
 */
import * as fs from 'fs';
import * as path from 'path';

const root = path.join(__dirname, '..');
const catalog = JSON.parse(fs.readFileSync(path.join(root, 'src/catalog/catalog.authoritative.json'), 'utf8'));

const RESERVED = new Set(['default', 'function', 'new', 'delete', 'in', 'class', 'var', 'let', 'const', 'this', 'return']);
const camel = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);
const sanitize = (n: string, i: number) => {
  let s = (n || `arg${i}`).replace(/[^A-Za-z0-9_]/g, '_');
  if (/^[0-9]/.test(s)) s = '_' + s;
  if (RESERVED.has(s)) s = s + '_';
  return s;
};
const isAccessor = (n: string) => /^(get_|set_|add_|remove_)/.test(n);

// kind -> TS param type
function tsType(kind: string): string {
  const base = kind.replace(/\?$/, '');
  const nul = kind.endsWith('?') ? ' | null' : '';
  switch (base) {
    case 'sooid': return 'Uint8Array' + nul;
    case 'prim:int': case 'prim:char': case 'enum': case 'prim:double': case 'prim:float': return 'number' + nul;
    case 'prim:long': return '(bigint | number)' + nul;
    case 'prim:bool': return 'boolean' + nul;
    case 'prim:string': return 'string | null';
    case 'ref': return 'bigint';
    case 'reflist': return '(bigint | number)[]';
    case 'bytes': return 'Uint8Array | null';
    case 'struct': return 'Record<string, unknown>';
    case 'primlist': return 'Buffer'; // pre-serialized (rare); caller supplies bytes
    default: return 'unknown';
  }
}

// kind -> expression producing a Buffer part, given the JS arg var `v` and the
// param's FQ type (for struct typeName).
function argExpr(kind: string, v: string, ptype: string): string {
  const base = kind.replace(/\?$/, '');
  switch (base) {
    case 'sooid': return `buildArgs([Arg.sooid(${v} ?? Buffer.alloc(0))])`;
    case 'prim:int': case 'prim:char': return `buildArgs([Arg.int(Number(${v} ?? 0))])`;
    case 'enum': return `buildArgs([Arg.enum_(Number(${v} ?? 0))])`;
    case 'prim:long': return `buildArgs([Arg.long((${v} ?? 0) as any)])`;
    case 'prim:bool': return `buildArgs([Arg.bool(Boolean(${v}))])`;
    case 'prim:double': case 'prim:float': return `buildArgs([Arg.double(Number(${v} ?? 0))])`;
    case 'prim:string': return `buildArgs([Arg.str(${v} ?? null)])`;
    case 'ref': return `buildArgs([Arg.ref(${v})])`;
    case 'reflist': return `buildArgs([Arg.refList(${v})])`;
    case 'bytes': return `buildArgs([Arg.bytes(${v} ?? null)])`;
    case 'struct': return `buildStruct(this.c, ${JSON.stringify(ptype)}, (${v} ?? {}))`;
    case 'primlist': return `(${v})`; // raw bytes
    default: return `Buffer.alloc(0)`;
  }
}

// the FQ Sooloos type for a struct param (from the catalog param.type which is
// already the wire-FQ form, e.g. "Sooloos.Broker.Api.PlayParameters").
function structTypeName(ptype: string): string {
  return ptype.replace(/\?$/, '');
}

let out = `// AUTO-GENERATED by tools/gen_client.ts — do not edit.
/* eslint-disable */
import { RoonClient } from '../proto/client';
import { CallResult } from '../proto/remoting';
import { Arg, buildArgs, inlineStruct, serializeStructValue } from '../proto/serializer';

const STRUCTS: Record<string, { name: string; propType: number }[]> = ${JSON.stringify(
  Object.fromEntries(Object.entries(catalog.structs).map(([k, v]: any) => [k, v.members.map((m: any) => ({ name: m.name, propType: m.propType }))])),
)};

function buildStruct(c: RoonClient, typeName: string, fields: Record<string, unknown>): Buffer {
  const members = STRUCTS[typeName] || [];
  const typeId = c.remoting.defineType(typeName, members);
  const entries: { index: number; value: Buffer }[] = [];
  for (const [k, val] of Object.entries(fields)) {
    const idx = members.findIndex((m) => m.name === k);
    if (idx < 0) continue;
    entries.push({ index: idx + 1, value: serializeStructValue(members[idx].propType, val) });
  }
  return inlineStruct(typeId, entries);
}

/** Base for a generated service bound to an object id. */
class ServiceBase {
  constructor(protected c: RoonClient, protected oid: bigint) {}
}
`;

const factoryEntries: string[] = [];

for (const svc of catalog.services) {
  const cls = `${svc.name.replace(/[^A-Za-z0-9_]/g, '_')}Api`;
  const seen = new Map<string, number>();
  let body = '';
  for (const m of svc.methods) {
    if (isAccessor(m.name)) continue;
    let mname = camel(m.name.replace(/[^A-Za-z0-9_]/g, '_'));
    const n = (seen.get(mname) || 0) + 1;
    seen.set(mname, n);
    if (n > 1) mname = `${mname}_${n}`;

    const params = (m.params || []).filter((p: any) => p.kind !== 'callback');
    const tsParams = params
      .map((p: any, i: number) => `${sanitize(p.name, i)}: ${tsType(p.kind)}`)
      .join(', ');
    const parts = params.map((p: any, i: number) => `      ${argExpr(p.kind, sanitize(p.name, i), structTypeName(p.type))},`).join('\n');
    const sig = JSON.stringify(m.signature);
    if (m.expectsResponse) {
      body += `  async ${mname}(${tsParams}): Promise<CallResult> {
    const parts: Buffer[] = [
${parts}
    ];
    return this.c.remoting.callMethod(this.oid, ${sig}, Buffer.concat(parts));
  }
`;
    } else {
      body += `  ${mname}(${tsParams}): void {
    const parts: Buffer[] = [
${parts}
    ];
    this.c.remoting.callMethodNoReply(this.oid, ${sig}, Buffer.concat(parts));
  }
`;
    }
  }
  out += `\nexport class ${cls} extends ServiceBase {\n${body}}\n`;
  factoryEntries.push(`  get ${camel(svc.name.replace(/[^A-Za-z0-9_]/g, '_'))}() { return new ${cls}(c, c.serviceOid(${JSON.stringify(svc.name)})); }`);
}

// A factory that lazily binds singleton services to their resolved object ids.
out += `\n/** Bind generated services to a connected client. Service singletons resolve\n * their object id via the object graph; entity classes can be constructed with\n * an explicit oid: new ZoneApi(client, zoneOid). */\nexport function makeApi(c: RoonClient) {\n  return {\n${factoryEntries.join(',\n')}\n  };\n}\n`;

const dir = path.join(root, 'src/generated');
fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(path.join(dir, 'api.ts'), out);
const methodCount = catalog.services.reduce((a: number, s: any) => a + s.methods.filter((m: any) => !isAccessor(m.name)).length, 0);
console.log(`generated src/generated/api.ts: ${catalog.services.length} services, ${methodCount} methods`);
