import * as fs from 'fs';
import * as path from 'path';

/**
 * Locks in that the authoritative catalog (generated by the C# oracle via
 * reflection over Roon.Broker.Api.dll) reproduces every DEFMETHOD signature
 * captured from the official client. Two independent sources (this + the
 * text-parse formatter in signature.test.ts) agree with ground truth.
 *
 * The authoritative catalog requires the oracle to have run (Roon installed +
 * dotnet). If it hasn't been generated, the test is skipped rather than failing
 * a fresh checkout.
 */
const authPath = path.join(__dirname, 'catalog.authoritative.json');
const capturedPath = path.join(__dirname, 'fixtures', 'captured_signatures.json');

const hasAuth = fs.existsSync(authPath);
const d = hasAuth ? describe : describe.skip;

d('authoritative catalog (C# oracle) vs captured ground truth', () => {
  const auth = hasAuth ? JSON.parse(fs.readFileSync(authPath, 'utf8')) : { services: [] };
  const captured: string[] = JSON.parse(fs.readFileSync(capturedPath, 'utf8'));
  const sigs = new Set<string>();
  for (const s of auth.services) for (const m of s.methods) sigs.add(m.signature);

  test('every captured DEFMETHOD signature is in the authoritative catalog', () => {
    const missing = captured.filter((c) => !sigs.has(c));
    expect(missing).toEqual([]);
  });

  test('catalog has the expected scale (>=1500 RPC methods, >=100 enums)', () => {
    const rpc = auth.services
      .flatMap((s: any) => s.methods)
      .filter((m: any) => !/^(get_|set_|add_|remove_)/.test(m.name)).length;
    expect(rpc).toBeGreaterThanOrEqual(1500);
    expect(auth.enumCount).toBeGreaterThanOrEqual(100);
  });

  // Phase A: by-val struct schemas + per-param kinds (validated vs working live calls).
  test('struct member schemas match the PropertyTypes used in working calls', () => {
    expect(auth.structCount).toBeGreaterThanOrEqual(290);
    const sp = auth.structs?.['Sooloos.Broker.Api.SearchParameters']?.members ?? [];
    const byName: Record<string, number> = {};
    for (const m of sp) byName[m.name] = m.propType;
    // PropertyType: Sooid=4, String=20, Int=0, Bool=2 (these drove the working UnifiedSearch)
    expect(byName.ProfileId).toBe(4);
    expect(byName.Terms).toBe(20);
    expect(byName.MaxCount).toBe(0);
    expect(byName.IsInstantSearch).toBe(2);
  });

  test('param kinds match the working PlayAlbum/FavoriteOrBan calls', () => {
    const kinds = (svc: string, method: string) => {
      const m = auth.services.find((s: any) => s.name === svc)?.methods.find((x: any) => x.name === method && x.signature.includes('AlbumBase'));
      return m?.params.map((p: any) => p.kind);
    };
    expect(kinds('Transport', 'PlayAlbum')).toEqual(['ref', 'sooid', 'struct', 'ref', 'prim:bool', 'prim:bool', 'callback']);
    expect(kinds('Library', 'FavoriteOrBan')).toEqual(['sooid', 'ref', 'enum', 'callback']);
  });
});
